version: '3'

services:
  hyperf:
    # build: .
    image: wuchuheng/a861_admin:cache
    restart: always
    ports:
      - "9527:9527"
    volumes:
      - ./:/opt/www/
    privileged: true
    command:
      - /bin/sh
      - -c
      - |
        yarn config set -g registry https://registry.npm.taobao.org
        yarn install
        yarn run dev
